import assert from 'node:assert/strict'
import test from 'node:test'
import { hasExpectedImageDimensions, readImageDimensions } from '../src/lib/image-file.ts'

function writeAscii(bytes: Uint8Array, offset: number, value: string) {
  bytes.set(new TextEncoder().encode(value), offset)
}

function png(width: number, height: number): Blob {
  const bytes = new Uint8Array(24)
  bytes.set([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])
  new DataView(bytes.buffer).setUint32(8, 13)
  writeAscii(bytes, 12, 'IHDR')
  const view = new DataView(bytes.buffer)
  view.setUint32(16, width)
  view.setUint32(20, height)
  return new Blob([bytes])
}

function webpExtended(width: number, height: number): Blob {
  const bytes = new Uint8Array(30)
  writeAscii(bytes, 0, 'RIFF')
  writeAscii(bytes, 8, 'WEBP')
  writeAscii(bytes, 12, 'VP8X')
  const widthMinusOne = width - 1
  const heightMinusOne = height - 1
  bytes.set(
    [widthMinusOne, widthMinusOne >> 8, widthMinusOne >> 16].map((value) => value & 0xff),
    24,
  )
  bytes.set(
    [heightMinusOne, heightMinusOne >> 8, heightMinusOne >> 16].map((value) => value & 0xff),
    27,
  )
  return new Blob([bytes])
}

test('reads dimensions from supported image headers without decoding', async () => {
  assert.deepEqual(await readImageDimensions(png(512, 512)), { width: 512, height: 512 })
  assert.deepEqual(await readImageDimensions(webpExtended(640, 480)), {
    width: 640,
    height: 480,
  })
})

test('accepts only the dimensions generated by VEIL', async () => {
  assert.equal(await hasExpectedImageDimensions(png(512, 512), 512, 512), true)
  assert.equal(await hasExpectedImageDimensions(png(8192, 8192), 512, 512), false)
})

test('rejects malformed and unsupported files', async () => {
  assert.equal(await readImageDimensions(new Blob([new Uint8Array(30)])), null)
  assert.equal(
    await readImageDimensions(new Blob([new TextEncoder().encode('not an image')])),
    null,
  )
})
